require "../buildr.rb"

VERSION_NUMBER = "0.1"
NEXT_VERSION = "0.2"
GROUP = "TimeTool"

PMD = "pmd:pmd:jar:4.1"
JODA_TIME = "joda-time:joda-time:jar:1.5"
ZONE_LAYOUT = "../3pp/zoneLayout-1.0b4/zoneLayout-1.0b4.jar"

repositories.remote << "http://www.ibiblio.org/maven2/"

define "TimeTool" do
	libs = JODA_TIME, ZONE_LAYOUT

  project.version = VERSION_NUMBER
  project.group = GROUP

  compile.with(libs)
  resources

	test.compile.with # Add classpath dependencies
  package(:jar)
end
